version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/api
    command: go run /api/main.go

  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
    command: bash -c "export PATH=5000 && cd /app && npm run serve"

